#!/usr/bin/env python

import json
import sys

stdin_data = json.loads(sys.stdin.read())

if stdin_data["type"] == "before_request":
    state = stdin_data["state"] or 0
    next_state = state + 1
    output = {
        "set_state": next_state,
        "add_headers": [{"name": "redirect-counter", "value": str(next_state)}],
    }
else:
    output = {}

print(json.dumps(output))
