#!/usr/bin/env python

import base64
import hashlib
import hmac
import json
import sys

stdin_data = json.loads(sys.stdin.read())

if stdin_data["type"] == "configure":
    output = {"requires_body": True}
elif stdin_data["type"] == "before_request":
    secret = stdin_data["auth"][0]
    body_base64 = stdin_data["request"]["body_base64"]

    output = {"add_headers": []}

    if body_base64 is not None:
        body = base64.b64decode(body_base64).decode("utf8")

        signature = hmac.new(
            secret.encode("utf8"), body.encode("utf8"), hashlib.sha256
        ).hexdigest()

        output["add_headers"].append({"name": "x-signature", "value": signature})
else:
    output = {}

print(json.dumps(output))
