#!/usr/bin/env python

import json
import sys
from urllib.parse import urlparse

stdin_data = json.loads(sys.stdin.read())
url = urlparse(stdin_data["next_request"]["url"])

output = {"add_headers": [], "remove_headers": []}

if url.hostname == "example.com":
    output["add_headers"].append({"name": "x-token", "value": "42"})

print(json.dumps(output))
