#!/usr/bin/env python

import base64
import hashlib
import hmac
import json
import sys

stdin_data = json.loads(sys.stdin.read())

secret = stdin_data["auth"][0]
body_base64 = stdin_data["next_request"]["body_base64"]

output = {"add_headers": [], "remove_headers": []}

if body_base64 is None:
    print(json.dumps(output))
    exit(0)

body = base64.b64decode(body_base64).decode("utf8")

signature = hmac.new(
    secret.encode("utf8"), body.encode("utf8"), hashlib.sha256
).hexdigest()

output["add_headers"].append({"name": "x-signature", "value": signature})

print(json.dumps(output))
