.TH XH 1 2022-08-29 0.16.1 "User Commands"

.SH NAME
xh \- Friendly and fast tool for sending HTTP requests

.SH SYNOPSIS
.B xh
[\fIOPTIONS\fR]
[\fIMETHOD\fR]
\fIURL\fR
[\-\-\]
[\fIREQUEST_ITEM\fR ...]

.SH DESCRIPTION

xh is an HTTP client that aims to reimplement as much as possible of
HTTPie's excellent design, with a focus on improved performance.

.SH POSITIONAL ARGUMENTS
.TP
[\fIMETHOD\fR]\fI
HTTP method to use for the request.

If the method is omitted, it will default to either GET or POST
depending on whether the request contains a body or not.
.TP
\fIURL\fR
The URL to request.

The URL scheme defaults to "http://" normally, or "https://" if
the program is invoked as "xhs".

A leading colon works as shorthand for localhost. ":8000" is equivalent
to "localhost:8000", and ":/path" is equivalent to "localhost/path".

URLs can have a leading "://" which allows quickly converting a URL
into a valid xh or HTTPie command. For example "http://httpbin.org/json"
becomes "http ://httpbin.org/json".
.TP
[\fIREQUEST_ITEM\fR ...]
Optional key\-value pairs to be included in the request

The separator is used to determine the type i.e. header, request body,
query string, etc. Possible REQUEST_ITEM types are:
.RS 12
.TP
key==value
Add a query string to the URL.
.TP
key=value
Add a JSON property (\-\-json) or form field (\-\-form) to the request body.
.TP
key=@file
Add a JSON property (\-\-json) or form field (\-\-form) from a file to the
request body.
.TP
key:=value
Add a field with literal JSON value to the request body, e.g. numbers:=[1,2,3]
enabled:=true.
.TP
key:=@file
Add a field with literal JSON value from a file to the request body.
.TP
key@file
Upload a file from filename (requires either \-\-form  or \-\-multipart).

To set  the filename and mimetype, ";type=" and ";filename=" can be used,
e.g. pfp@ra.jpg;type=image/jpeg;filename=profile.jpg
.TP
@filename
Use a file as the request body.
.TP
header:value
Add a header, e.g. user\-agent:foobar
.TP
header:
Unset a header, e.g. connection:
.TP
header;
Add a header with an empty value.
.RE

.RS
A backslash can be used to escape special characters, e.g. weird\\:key=value.

To construct a complex JSON object, the REQUEST_ITEM's key can be set to a JSON path
instead of a field name. For more information on the nested json syntax, refer to
<https://httpie.io/docs/cli/nested\-json>.
.RE

.SH OPTIONS
Each --OPTION can be reset with a --no-OPTION argument.
.TP
\fB\-j\fR, \fB\-\-json\fR
(default) Serialize data items from the command line as a JSON object.

Overrides both \-\-form and \-\-multipart.
.TP
\fB\-f\fR, \fB\-\-form\fR
Serialize data items from the command line as form fields.

Overrides both \-\-json and \-\-multipart.
.TP
\fB\-m\fR, \fB\-\-multipart\fR
Like \-\-form, but force a multipart/form\-data request even without files.

Overrides both \-\-json and \-\-form.
.TP
\fB\-\-raw\fR=\fIRAW\fR
Pass raw request data without extra processing
.TP
\fB\-\-pretty\fR=\fISTYLE\fR
Controls output processing. Possible values are:

    all      (default) Enable both coloring and formatting
    colors   Apply syntax highlighting to output
    format   Pretty\-print json and sort headers
    none     Disable both coloring and formatting

Defaults to "format" if the NO_COLOR env is set and to "none" if stdout is not tty.
.TP
\fB\-s\fR, \fB\-\-style\fR=\fITHEME\fR
Output coloring style

[possible values: auto, solarized, monokai, fruity]
.TP
\fB\-\-response\-charset\fR=\fIENCODING\fR
Override the response encoding for terminal display purposes.

Example: \-\-response\-charset=latin1
.TP
\fB\-\-response\-mime\fR=\fIMIME_TYPE\fR
Override the response mime type for coloring and formatting for the terminal

Example: \-\-response\-mime=application/json
.TP
\fB\-p\fR, \fB\-\-print\fR=\fIFORMAT\fR
String specifying what the output should contain.

Use "H" and "B" for request header and body respectively, and "h" and "b" for response header and body.

Example: \-\-print=Hb
.TP
\fB\-h\fR, \fB\-\-headers\fR
Print only the response headers. Shortcut for \-\-print=h
.TP
\fB\-b\fR, \fB\-\-body\fR
Print only the response body. Shortcut for \-\-print=b
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Print the whole request as well as the response.

Additionally, this enables \-\-all for printing intermediary requests/responses while following redirects.

Equivalent to \-\-print=HhBb \-\-all.
.TP
\fB\-\-all\fR
Show any intermediary requests/responses while following redirects with \-\-follow
.TP
\fB\-P\fR, \fB\-\-history\-print\fR=\fIFORMAT\fR
The same as \-\-print but applies only to intermediary requests/responses
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Do not print to stdout or stderr
.TP
\fB\-S\fR, \fB\-\-stream\fR
Always stream the response body
.TP
\fB\-o\fR, \fB\-\-output\fR=\fIFILE\fR
Save output to FILE instead of stdout
.TP
\fB\-d\fR, \fB\-\-download\fR
Download the body to a file instead of printing it.

The Accept\-Encoding header is set to identify and any redirects will be followed.
.TP
\fB\-c\fR, \fB\-\-continue\fR
Resume an interrupted download. Requires \-\-download and \-\-output
.TP
\fB\-\-session\fR=\fIFILE\fR
Create, or reuse and update a session.

Within a session, custom headers, auth credentials, as well as any cookies sent by the server persist between requests.
.TP
\fB\-\-session\-read\-only\fR=\fIFILE\fR
Create or read a session without updating it form the request/response exchange
.TP
\fB\-A\fR, \fB\-\-auth\-type\fR=\fIAUTH_TYPE\fR
Specify the auth mechanism

[possible values: basic, bearer, digest]
.TP
\fB\-a\fR, \fB\-\-auth\fR=\fIUSER\fR[\fI:PASS\fR] | \fITOKEN\fR
Authenticate as USER with PASS (\-A basic|digest) or with TOKEN (\-A bearer).

PASS will be prompted if missing. Use a trailing colon (i.e. "USER:") to authenticate with just a username.

TOKEN is expected if \-\-auth\-type=bearer.
.TP
\fB\-\-ignore\-netrc\fR
Do not use credentials from .netrc
.TP
\fB\-\-offline\fR
Construct HTTP requests without sending them anywhere
.TP
\fB\-\-check\-status\fR
(default) Exit with an error status code if the server replies with an error.

The exit code will be 4 on 4xx (Client Error), 5 on 5xx (Server Error), or 3 on 3xx (Redirect) if \-\-follow isn't set.

If stdout is redirected then a warning is written to stderr.
.TP
\fB\-F\fR, \fB\-\-follow\fR
Do follow redirects
.TP
\fB\-\-max\-redirects\fR=\fINUM\fR
Number of redirects to follow. Only respected if \-\-follow is used
.TP
\fB\-\-timeout\fR=\fISEC\fR
Connection timeout of the request.

The default value is "0", i.e., there is no timeout limit.
.TP
\fB\-\-proxy\fR=\fIPROTOCOL:URL\fR
Use a proxy for a protocol. For example: \-\-proxy https:http://proxy.host:8080.

PROTOCOL can be "http", "https" or "all".

If your proxy requires credentials, put them in the URL, like so: \-\-proxy http:socks5://user:password@proxy.host:8000.

You can specify proxies for multiple protocols by repeating this option.

The environment variables "http_proxy" and "https_proxy" can also be used, but are completely ignored if \-\-proxy is passed.
.TP
\fB\-\-verify\fR=\fIVERIFY\fR
If "no", skip SSL verification. If a file path, use it as a CA bundle.

Specifying a CA bundle will disable the system's built\-in root certificates.

"false" instead of "no" also works. The default is "yes" ("true").
.TP
\fB\-\-cert\fR=\fIFILE\fR
Use a client side certificate for SSL
.TP
\fB\-\-cert\-key\fR=\fIFILE\fR
A private key file to use with \-\-cert.

Only necessary if the private key is not contained in the cert file.
.TP
\fB\-\-ssl\fR=\fIVERSION\fR
Force a particular TLS version.

"auto" gives the default behavior of negotiating a version with the server.

[possible values: auto, tls1, tls1.1, tls1.2, tls1.3]
.TP
\fB\-\-native\-tls\fR
Use the system TLS library instead of rustls (if enabled at compile time)
.TP
\fB\-\-https\fR
Make HTTPS requests if not specified in the URL
.TP
\fB\-\-http\-version\fR=\fIVERSION\fR
HTTP version to use

[possible values: 1.0, 1.1, 2]
.TP
\fB\-I\fR, \fB\-\-ignore\-stdin\fR
Do not attempt to read stdin.

By default, stdin's TTY status is checked to detect redirected input and, in turn, read the request body from stdin.

For example: cat report.txt | xh post example.com

However, this might cause xh to hang in certain non\-interactive sessions e.g. cron jobs, so \-\-ignore\-stdin should be used to opt\-out of this behavior.
.TP
\fB\-\-curl\fR
Print a translation to a curl command.

For translating the other way, try https://curl2httpie.online/.
.TP
\fB\-\-curl\-long\fR
Use the long versions of curl's flags
.TP
\fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information

.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B 1
Usage, syntax or network error.
.TP
.B 2
Request timeout.
.TP
.B 3
Unexpected HTTP 3xx Redirection.
.TP
.B 4
HTTP 4xx Client Error.
.TP
.B 5
HTTP 5xx Server Error.
.TP
.B 6
Too many redirects.

.SH ENVIRONMENT
.TP
.B XH_CONFIG_DIR
Specifies where to look for config.json and named session data.
The default is ~/.config/xh for Linux/macOS and %APPDATA%\\xh for Windows.
.TP
.B XH_HTTPIE_COMPAT_MODE
Enables the HTTPie Compatibility Mode. The only current difference is that
\-\-check-status is not enabled by default. An alternative to setting this
environment variable is to rename the binary to either http or https.
.TP
.BR REQUESTS_CA_BUNDLE ", " CURL_CA_BUNDLE
Sets a custom CA bundle path.
.TP
.B HTTPS_PROXY
Sets the proxy server to use for HTTPS.
.TP
.B http_proxy
Sets the proxy server to use for HTTP.
.TP
.B NETRC
Location of the .netrc file.
.TP
.B NO_COLOR
Disables output coloring. See <https://no-color.org>

.SH FILES
.TP
.I ~/.config/xh/config.json
xh configuration file. The only configurable option is "default_options"
which is a list of default shell arguments that gets passed to xh.
Example:

.RS
{ "default_options": ["--native-tls", "--style=solarized"] }
.RE
.TP
.IR ~/.netrc ", " ~/_netrc
Auto-login information file.
.TP
.I ~/.config/xh/sessions
Session data directory grouped by domain and port number.

.SH EXAMPLES
.TP 4
\fBxh\fR \fIhttpbin.org/json\fR
Send a GET request.
.TP
\fBxh\fR \fIhttpbin.org/post name=ahmed \fIage:=24\fR
Send a POST request with body {"name": "ahmed", "age": 24}.
.TP
\fBxh\fR get \fIhttpbin.org/json id==5 sort==true\fR
Send a GET request with querystring id=5&sort=true.
.TP
\fBxh\fR get \fIhttpbin.org/json x-api-key:12345\fR
Send a GET request and include a header named x-api-key with value 12345.
.TP
\fBxh\fR put \fIhttpbin.org/put id:=49 age:=25\fR | less
Send a PUT request and pipe the result to less.
.TP
\fBxh\fR -d \fIhttpbin.org/json\fR -o \fIres.json\fR
Download and save to res.json.
.TP
\fBxh\fR \fIhttpbin.org/get user-agent:foobar\fR
Make a request with a custom user agent.
.TP
\fBxhs\fR \fIexample.com\fR
Make an HTTPS request to https://example.com.

.SH REPORTING BUGS
xh's Github issues <https://github.com/ducaale/xh/issues>

.SH SEE ALSO
\fBcurl\fR(1), \fBhttp\fR(1)

HTTPie's online documentation <https://httpie.io/docs/cli>
